"""Deployment mode and request-owned storage context."""
import os
from contextvars import ContextVar
from pathlib import Path

user_context = ContextVar("daymark_user", default=None)


def cloud_enabled():
    return os.environ.get("DAYMARK_MODE", "local") == "cloud"


def cloud_data():
    return Path(os.environ.get("DAYMARK_DATA_DIR", str(Path(__file__).resolve().parents[2] / "data"))).resolve()


def current_user_id():
    value = user_context.get()
    if not value:
        raise RuntimeError("Authenticated user context is required")
    return value


def user_directory(user_id=None):
    # IDs are generated by the account service, never accepted from a URL.
    value = user_id or current_user_id()
    from uuid import UUID
    if str(UUID(value)) != value:
        raise ValueError("Invalid user ID")
    return cloud_data() / "users" / value
