"""Initial planning schema"""
from alembic import op
import sqlalchemy as sa

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reviews',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('project_minutes', sa.JSON(), nullable=False),
    sa.Column('completed_tasks', sa.JSON(), nullable=False),
    sa.Column('unfinished_tasks', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('goals',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('target_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('day_start', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_goal_id'), ['goal_id'], unique=False)

    op.create_table('milestones',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('deadline', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)

    op.create_table('routines',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('milestone_id', sa.String(length=36), nullable=True),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('interval_unit', sa.String(), nullable=False),
    sa.Column('weekdays', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('preferred_time', sa.String(length=5), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reminder', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('depends_on_routine_id', sa.String(length=36), nullable=True),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('materialized_through', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint('interval >= 1'),
    sa.CheckConstraint('offset_days >= 0'),
    sa.ForeignKeyConstraint(['depends_on_routine_id'], ['routines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routines_project_id'), ['project_id'], unique=False)

    op.create_table('tasks',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('milestone_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('routine_id', sa.String(length=36), nullable=True),
    sa.Column('occurrence_date', sa.String(length=10), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('depends_on_task_id', sa.String(length=36), nullable=True),
    sa.Column('depends_on_routine_id', sa.String(length=36), nullable=True),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('reminder', sa.Integer(), nullable=True),
    sa.Column('is_exception', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('pending','completed','overdue','rescheduled','cancelled')"),
    sa.CheckConstraint('estimated_duration >= 0'),
    sa.CheckConstraint('priority BETWEEN 1 AND 3'),
    sa.ForeignKeyConstraint(['depends_on_routine_id'], ['routines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'occurrence_date', name='uq_routine_occurrence')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('calendar_events',
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start', sa.String(), nullable=False),
    sa.Column('end', sa.String(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_range', ['start', 'end'], unique=False)

    op.create_table('reminder_jobs',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('due_at', sa.String(), nullable=False),
    sa.Column('task_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'task_version', name='uq_reminder_version')
    )
    with op.batch_alter_table('reminder_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_jobs_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_jobs_task_id'), ['task_id'], unique=False)

    op.create_table('task_history',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_history_task_id'), ['task_id'], unique=False)

    op.create_table('notifications',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_at', sa.String(), nullable=False),
    sa.Column('read_at', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['reminder_jobs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_history_task_id'))

    op.drop_table('task_history')
    with op.batch_alter_table('reminder_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_jobs_task_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_jobs_due_at'))

    op.drop_table('reminder_jobs')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_range')

    op.drop_table('calendar_events')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_deadline'))
        batch_op.drop_index(batch_op.f('ix_tasks_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_completed_at'))

    op.drop_table('tasks')
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routines_project_id'))

    op.drop_table('routines')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_goal_id'))

    op.drop_table('projects')
    op.drop_table('settings')
    op.drop_table('goals')
    op.drop_table('daily_reviews')
    # ### end Alembic commands ###
