from .permissions import ToolPermission as P
from .tool_arguments import (
    CreateEventArgs, CreateGoalArgs, CreateLearningEntryArgs, CreateMilestoneArgs,
    CreateProjectArgs, CreateRoutineArgs, CreateTaskArgs, DeleteTaskArgs, EmptyArgs,
    EventIdArgs, GetCalendarArgs, GetDocumentsArgs, GetFreeSlotsArgs, GetLearningEntriesArgs,
    GetOrganizationArgs, GetTasksArgs, ImportTimetableArgs, NotificationIdArgs, RecordIdArgs,
    ReplanDayArgs, RescheduleTaskArgs, ReviewArgs, RoutineIdArgs, SaveAttachmentArgs,
    SaveReviewArgs, ScheduleTaskArgs, StatisticsArgs, TaskIdArgs, UpcomingArgs,
    UpdateDocumentArgs, UpdateEventArgs, UpdateGoalArgs, UpdateLearningEntryArgs,
    UpdateMilestoneArgs, UpdateProjectArgs, UpdateRoutineArgs, UpdateSettingsArgs, UpdateTaskArgs,
    UpdateAISettingsArgs,
)
from .tool_registry import ToolDefinition, ToolRegistry


def build_registry():
    registry = ToolRegistry()
    definitions = [
        ("get_today_tasks", "读取今天的全部真实任务。", EmptyArgs, P.READ, "正在读取今天的任务…"),
        ("get_tasks", "按日期、项目或状态查询真实任务。date/start_date/end_date 使用 YYYY-MM-DD。", GetTasksArgs, P.READ, "正在查询任务…"),
        ("get_calendar", "读取指定日期范围的任务和独立日历事项。", GetCalendarArgs, P.READ, "正在读取日历…"),
        ("get_free_slots", "用确定性代码计算某天空闲时间。time 使用 HH:MM。", GetFreeSlotsArgs, P.READ, "正在检查空闲时间…"),
        ("get_routines", "读取全部有效重复任务。", EmptyArgs, P.READ, "正在读取重复任务…"),
        ("get_upcoming_deadlines", "读取未来若干天的截止事项。", UpcomingArgs, P.READ, "正在读取临近截止事项…"),
        ("get_goals", "读取目标，可按状态筛选。", GetOrganizationArgs, P.READ, "正在读取目标…"),
        ("create_goal", "创建长期目标。", CreateGoalArgs, P.WRITE, "正在创建目标…"),
        ("update_goal", "修改目标；先查询取得真实 record_id。", UpdateGoalArgs, P.WRITE, "正在更新目标…"),
        ("delete_goal", "删除没有关联项目的目标；需要用户确认。", RecordIdArgs, P.DESTRUCTIVE, "正在准备删除目标…"),
        ("get_projects", "读取项目，可按状态筛选。", GetOrganizationArgs, P.READ, "正在读取项目…"),
        ("create_project", "创建项目，可关联已有目标。", CreateProjectArgs, P.WRITE, "正在创建项目…"),
        ("update_project", "修改项目；先查询取得真实 record_id。", UpdateProjectArgs, P.WRITE, "正在更新项目…"),
        ("delete_project", "删除没有关联内容的项目；需要用户确认。", RecordIdArgs, P.DESTRUCTIVE, "正在准备删除项目…"),
        ("get_milestones", "读取里程碑，可按状态筛选。", GetOrganizationArgs, P.READ, "正在读取里程碑…"),
        ("create_milestone", "在已有项目下创建里程碑。", CreateMilestoneArgs, P.WRITE, "正在创建里程碑…"),
        ("update_milestone", "修改里程碑；先查询取得真实 record_id。", UpdateMilestoneArgs, P.WRITE, "正在更新里程碑…"),
        ("delete_milestone", "删除没有关联任务的里程碑；需要用户确认。", RecordIdArgs, P.DESTRUCTIVE, "正在准备删除里程碑…"),
        ("create_task", "在规划系统中创建任务。用户给出明确开始时间时必须使用本工具并原样保留该时间；会检测冲突。date 必须为 YYYY-MM-DD，开始时间字段必须名为 start_time 且值为 HH:MM。", CreateTaskArgs, P.WRITE, "正在创建任务…"),
        ("update_task", "修改指定任务的字段；需要先查询任务取得精确 task_id。", UpdateTaskArgs, P.WRITE, "正在更新任务…"),
        ("reschedule_task", "更改指定任务日期和时间并检测冲突。", RescheduleTaskArgs, P.WRITE, "正在重新安排任务…"),
        ("complete_task", "将指定任务标记为完成。", TaskIdArgs, P.WRITE, "正在完成任务…"),
        ("reopen_task", "重新打开已完成或已取消的任务。", TaskIdArgs, P.WRITE, "正在重新打开任务…"),
        ("cancel_task", "取消指定任务但保留记录。", TaskIdArgs, P.WRITE, "正在取消任务…"),
        ("keep_task_overdue", "保留逾期任务，不自动改期。", TaskIdArgs, P.WRITE, "正在保留逾期任务…"),
        ("create_routine", "创建重复任务规则并生成计划实例。", CreateRoutineArgs, P.WRITE, "正在创建重复任务…"),
        ("import_timetable", "把已经从附件课表中准确识别出的课程批量导入为每周重复任务。必须提供明确的学期开始和结束日期、课程名、星期英文名（monday 到 sunday）和上下课时间；执行前会让用户确认。", ImportTimetableArgs, P.WRITE, "正在准备课表导入预览…"),
        ("update_routine", "修改指定重复任务。", UpdateRoutineArgs, P.WRITE, "正在更新重复任务…"),
        ("pause_routine", "暂停指定重复任务。", RoutineIdArgs, P.WRITE, "正在暂停重复任务…"),
        ("delete_routine", "删除重复任务规则并取消可变更的未来实例；需要用户确认。", RoutineIdArgs, P.DESTRUCTIVE, "正在准备删除重复任务…"),
        ("create_event", "创建不属于 Task 的独立日历事项；start/end 使用本地 ISO 日期时间。", CreateEventArgs, P.WRITE, "正在创建日历事项…"),
        ("update_event", "修改独立日历事项；先从日历查询真实 event_id。", UpdateEventArgs, P.WRITE, "正在更新日历事项…"),
        ("delete_event", "删除独立日历事项；需要用户确认。", EventIdArgs, P.DESTRUCTIVE, "正在准备删除日历事项…"),
        ("get_learning_entries", "查询学习档案记录。", GetLearningEntriesArgs, P.READ, "正在读取学习档案…"),
        ("create_learning_entry", "创建学习、作业、阅读、研究等学习档案记录。", CreateLearningEntryArgs, P.WRITE, "正在创建学习记录…"),
        ("update_learning_entry", "修改学习档案记录；先查询取得真实 record_id。", UpdateLearningEntryArgs, P.WRITE, "正在更新学习记录…"),
        ("delete_learning_entry", "删除学习档案记录；需要用户确认。", RecordIdArgs, P.DESTRUCTIVE, "正在准备删除学习记录…"),
        ("get_documents", "查询知识库文档元数据。", GetDocumentsArgs, P.READ, "正在读取知识库…"),
        ("save_attachment_to_knowledge", "把当前对话中已经上传的附件长期保存到知识库。filename 必须与附件名一致。", SaveAttachmentArgs, P.WRITE, "正在保存附件到知识库…"),
        ("update_document", "修改知识库文档的标题、日期、项目、类型等元数据。", UpdateDocumentArgs, P.WRITE, "正在更新知识文档…"),
        ("delete_document", "从知识库删除文档记录；需要用户确认，原文件保留。", RecordIdArgs, P.DESTRUCTIVE, "正在准备删除知识文档…"),
        ("get_daily_review", "读取指定日期的每日复盘及任务快照。", ReviewArgs, P.READ, "正在读取每日复盘…"),
        ("save_daily_review", "保存指定日期的实际投入、精力、笔记和项目时间。", SaveReviewArgs, P.WRITE, "正在保存每日复盘…"),
        ("get_statistics", "读取指定日期或范围的完成率、计划/实际时间和项目分布。", StatisticsArgs, P.READ, "正在读取数据统计…"),
        ("get_progress", "读取目标、项目、里程碑的真实任务进度。", EmptyArgs, P.READ, "正在读取整体进度…"),
        ("get_settings", "读取时区和每日默认开始时间。", EmptyArgs, P.READ, "正在读取偏好设置…"),
        ("update_settings", "修改时区或每日默认开始时间。", UpdateSettingsArgs, P.WRITE, "正在更新偏好设置…"),
        ("get_notifications", "读取站内提醒通知。", EmptyArgs, P.READ, "正在读取通知…"),
        ("mark_notification_read", "把指定站内通知标记为已读。", NotificationIdArgs, P.WRITE, "正在更新通知…"),
        ("get_ai_settings", "读取 AI 模式、本地模型、上下文长度、温度和 Thinking 设置；不读取 API Key。", EmptyArgs, P.READ, "正在读取模型设置…"),
        ("update_ai_settings", "修改未来对话使用的 AI 模式和模型参数；不能修改 API Key。", UpdateAISettingsArgs, P.WRITE, "正在更新模型设置…"),
        ("prepare_data_export", "生成完整本地数据导出的下载入口。", EmptyArgs, P.READ, "正在准备数据导出…"),
        ("schedule_task", "仅当用户没有给出明确开始时间、要求‘找个时间’时，在指定范围中寻找空闲时段并创建任务。明确时间必须用 create_task。", ScheduleTaskArgs, P.WRITE, "正在寻找时间并安排任务…"),
        ("replan_day", "将与明确占用时段冲突的任务尽量重新安排到当天其他空闲时间。", ReplanDayArgs, P.WRITE, "正在重新安排冲突任务…"),
        ("undo_last_action", "撤销当前会话最近一次可撤销的任务操作。", EmptyArgs, P.WRITE, "正在撤销最近操作…"),
        ("delete_task", "永久从正常视图删除指定任务；必须由用户确认保存的原始动作。", DeleteTaskArgs, P.DESTRUCTIVE, "正在准备删除任务…"),
    ]
    for name, description, arguments, permission, status in definitions:
        registry.register(ToolDefinition(name, description, arguments, permission, status, name))
    return registry
